apiVersion: apps/v1
kind:
metadata:
  name:
spec:
  replica:
    selector:
      matchlabel:
        app: 
  template:
    metadata:
      labels:
        app:
    spec:
      containers:
      - name: nginx
        image: 
        port:
        - containerPort:
